// Code generated by ent, DO NOT EDIT.

package workflowrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldID, id))
}

// GroveID applies equality check predicate on the "grove_id" field. It's identical to GroveIDEQ.
func GroveID(v uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldGroveID, v))
}

// BrokerID applies equality check predicate on the "broker_id" field. It's identical to BrokerIDEQ.
func BrokerID(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldBrokerID, v))
}

// SourceYaml applies equality check predicate on the "source_yaml" field. It's identical to SourceYamlEQ.
func SourceYaml(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldSourceYaml, v))
}

// InputsJSON applies equality check predicate on the "inputs_json" field. It's identical to InputsJSONEQ.
func InputsJSON(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldInputsJSON, v))
}

// ResultJSON applies equality check predicate on the "result_json" field. It's identical to ResultJSONEQ.
func ResultJSON(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldResultJSON, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldErrorMessage, v))
}

// TraceURL applies equality check predicate on the "trace_url" field. It's identical to TraceURLEQ.
func TraceURL(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldTraceURL, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldFinishedAt, v))
}

// CreatedByUserID applies equality check predicate on the "created_by_user_id" field. It's identical to CreatedByUserIDEQ.
func CreatedByUserID(v uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedByAgentID applies equality check predicate on the "created_by_agent_id" field. It's identical to CreatedByAgentIDEQ.
func CreatedByAgentID(v uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldCreatedByAgentID, v))
}

// Created applies equality check predicate on the "created" field. It's identical to CreatedEQ.
func Created(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldCreated, v))
}

// Updated applies equality check predicate on the "updated" field. It's identical to UpdatedEQ.
func Updated(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldUpdated, v))
}

// GroveIDEQ applies the EQ predicate on the "grove_id" field.
func GroveIDEQ(v uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldGroveID, v))
}

// GroveIDNEQ applies the NEQ predicate on the "grove_id" field.
func GroveIDNEQ(v uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldGroveID, v))
}

// GroveIDIn applies the In predicate on the "grove_id" field.
func GroveIDIn(vs ...uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldGroveID, vs...))
}

// GroveIDNotIn applies the NotIn predicate on the "grove_id" field.
func GroveIDNotIn(vs ...uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldGroveID, vs...))
}

// BrokerIDEQ applies the EQ predicate on the "broker_id" field.
func BrokerIDEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldBrokerID, v))
}

// BrokerIDNEQ applies the NEQ predicate on the "broker_id" field.
func BrokerIDNEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldBrokerID, v))
}

// BrokerIDIn applies the In predicate on the "broker_id" field.
func BrokerIDIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldBrokerID, vs...))
}

// BrokerIDNotIn applies the NotIn predicate on the "broker_id" field.
func BrokerIDNotIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldBrokerID, vs...))
}

// BrokerIDGT applies the GT predicate on the "broker_id" field.
func BrokerIDGT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldBrokerID, v))
}

// BrokerIDGTE applies the GTE predicate on the "broker_id" field.
func BrokerIDGTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldBrokerID, v))
}

// BrokerIDLT applies the LT predicate on the "broker_id" field.
func BrokerIDLT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldBrokerID, v))
}

// BrokerIDLTE applies the LTE predicate on the "broker_id" field.
func BrokerIDLTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldBrokerID, v))
}

// BrokerIDContains applies the Contains predicate on the "broker_id" field.
func BrokerIDContains(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContains(FieldBrokerID, v))
}

// BrokerIDHasPrefix applies the HasPrefix predicate on the "broker_id" field.
func BrokerIDHasPrefix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasPrefix(FieldBrokerID, v))
}

// BrokerIDHasSuffix applies the HasSuffix predicate on the "broker_id" field.
func BrokerIDHasSuffix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasSuffix(FieldBrokerID, v))
}

// BrokerIDIsNil applies the IsNil predicate on the "broker_id" field.
func BrokerIDIsNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIsNull(FieldBrokerID))
}

// BrokerIDNotNil applies the NotNil predicate on the "broker_id" field.
func BrokerIDNotNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotNull(FieldBrokerID))
}

// BrokerIDEqualFold applies the EqualFold predicate on the "broker_id" field.
func BrokerIDEqualFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEqualFold(FieldBrokerID, v))
}

// BrokerIDContainsFold applies the ContainsFold predicate on the "broker_id" field.
func BrokerIDContainsFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContainsFold(FieldBrokerID, v))
}

// SourceYamlEQ applies the EQ predicate on the "source_yaml" field.
func SourceYamlEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldSourceYaml, v))
}

// SourceYamlNEQ applies the NEQ predicate on the "source_yaml" field.
func SourceYamlNEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldSourceYaml, v))
}

// SourceYamlIn applies the In predicate on the "source_yaml" field.
func SourceYamlIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldSourceYaml, vs...))
}

// SourceYamlNotIn applies the NotIn predicate on the "source_yaml" field.
func SourceYamlNotIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldSourceYaml, vs...))
}

// SourceYamlGT applies the GT predicate on the "source_yaml" field.
func SourceYamlGT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldSourceYaml, v))
}

// SourceYamlGTE applies the GTE predicate on the "source_yaml" field.
func SourceYamlGTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldSourceYaml, v))
}

// SourceYamlLT applies the LT predicate on the "source_yaml" field.
func SourceYamlLT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldSourceYaml, v))
}

// SourceYamlLTE applies the LTE predicate on the "source_yaml" field.
func SourceYamlLTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldSourceYaml, v))
}

// SourceYamlContains applies the Contains predicate on the "source_yaml" field.
func SourceYamlContains(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContains(FieldSourceYaml, v))
}

// SourceYamlHasPrefix applies the HasPrefix predicate on the "source_yaml" field.
func SourceYamlHasPrefix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasPrefix(FieldSourceYaml, v))
}

// SourceYamlHasSuffix applies the HasSuffix predicate on the "source_yaml" field.
func SourceYamlHasSuffix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasSuffix(FieldSourceYaml, v))
}

// SourceYamlEqualFold applies the EqualFold predicate on the "source_yaml" field.
func SourceYamlEqualFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEqualFold(FieldSourceYaml, v))
}

// SourceYamlContainsFold applies the ContainsFold predicate on the "source_yaml" field.
func SourceYamlContainsFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContainsFold(FieldSourceYaml, v))
}

// InputsJSONEQ applies the EQ predicate on the "inputs_json" field.
func InputsJSONEQ(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldInputsJSON, v))
}

// InputsJSONNEQ applies the NEQ predicate on the "inputs_json" field.
func InputsJSONNEQ(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldInputsJSON, v))
}

// InputsJSONIn applies the In predicate on the "inputs_json" field.
func InputsJSONIn(vs ...[]byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldInputsJSON, vs...))
}

// InputsJSONNotIn applies the NotIn predicate on the "inputs_json" field.
func InputsJSONNotIn(vs ...[]byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldInputsJSON, vs...))
}

// InputsJSONGT applies the GT predicate on the "inputs_json" field.
func InputsJSONGT(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldInputsJSON, v))
}

// InputsJSONGTE applies the GTE predicate on the "inputs_json" field.
func InputsJSONGTE(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldInputsJSON, v))
}

// InputsJSONLT applies the LT predicate on the "inputs_json" field.
func InputsJSONLT(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldInputsJSON, v))
}

// InputsJSONLTE applies the LTE predicate on the "inputs_json" field.
func InputsJSONLTE(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldInputsJSON, v))
}

// InputsJSONIsNil applies the IsNil predicate on the "inputs_json" field.
func InputsJSONIsNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIsNull(FieldInputsJSON))
}

// InputsJSONNotNil applies the NotNil predicate on the "inputs_json" field.
func InputsJSONNotNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotNull(FieldInputsJSON))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldStatus, vs...))
}

// ResultJSONEQ applies the EQ predicate on the "result_json" field.
func ResultJSONEQ(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldResultJSON, v))
}

// ResultJSONNEQ applies the NEQ predicate on the "result_json" field.
func ResultJSONNEQ(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldResultJSON, v))
}

// ResultJSONIn applies the In predicate on the "result_json" field.
func ResultJSONIn(vs ...[]byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldResultJSON, vs...))
}

// ResultJSONNotIn applies the NotIn predicate on the "result_json" field.
func ResultJSONNotIn(vs ...[]byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldResultJSON, vs...))
}

// ResultJSONGT applies the GT predicate on the "result_json" field.
func ResultJSONGT(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldResultJSON, v))
}

// ResultJSONGTE applies the GTE predicate on the "result_json" field.
func ResultJSONGTE(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldResultJSON, v))
}

// ResultJSONLT applies the LT predicate on the "result_json" field.
func ResultJSONLT(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldResultJSON, v))
}

// ResultJSONLTE applies the LTE predicate on the "result_json" field.
func ResultJSONLTE(v []byte) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldResultJSON, v))
}

// ResultJSONIsNil applies the IsNil predicate on the "result_json" field.
func ResultJSONIsNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIsNull(FieldResultJSON))
}

// ResultJSONNotNil applies the NotNil predicate on the "result_json" field.
func ResultJSONNotNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotNull(FieldResultJSON))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContainsFold(FieldErrorMessage, v))
}

// TraceURLEQ applies the EQ predicate on the "trace_url" field.
func TraceURLEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldTraceURL, v))
}

// TraceURLNEQ applies the NEQ predicate on the "trace_url" field.
func TraceURLNEQ(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldTraceURL, v))
}

// TraceURLIn applies the In predicate on the "trace_url" field.
func TraceURLIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldTraceURL, vs...))
}

// TraceURLNotIn applies the NotIn predicate on the "trace_url" field.
func TraceURLNotIn(vs ...string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldTraceURL, vs...))
}

// TraceURLGT applies the GT predicate on the "trace_url" field.
func TraceURLGT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldTraceURL, v))
}

// TraceURLGTE applies the GTE predicate on the "trace_url" field.
func TraceURLGTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldTraceURL, v))
}

// TraceURLLT applies the LT predicate on the "trace_url" field.
func TraceURLLT(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldTraceURL, v))
}

// TraceURLLTE applies the LTE predicate on the "trace_url" field.
func TraceURLLTE(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldTraceURL, v))
}

// TraceURLContains applies the Contains predicate on the "trace_url" field.
func TraceURLContains(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContains(FieldTraceURL, v))
}

// TraceURLHasPrefix applies the HasPrefix predicate on the "trace_url" field.
func TraceURLHasPrefix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasPrefix(FieldTraceURL, v))
}

// TraceURLHasSuffix applies the HasSuffix predicate on the "trace_url" field.
func TraceURLHasSuffix(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldHasSuffix(FieldTraceURL, v))
}

// TraceURLIsNil applies the IsNil predicate on the "trace_url" field.
func TraceURLIsNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIsNull(FieldTraceURL))
}

// TraceURLNotNil applies the NotNil predicate on the "trace_url" field.
func TraceURLNotNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotNull(FieldTraceURL))
}

// TraceURLEqualFold applies the EqualFold predicate on the "trace_url" field.
func TraceURLEqualFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEqualFold(FieldTraceURL, v))
}

// TraceURLContainsFold applies the ContainsFold predicate on the "trace_url" field.
func TraceURLContainsFold(v string) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldContainsFold(FieldTraceURL, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotNull(FieldFinishedAt))
}

// CreatedByUserIDEQ applies the EQ predicate on the "created_by_user_id" field.
func CreatedByUserIDEQ(v uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDNEQ applies the NEQ predicate on the "created_by_user_id" field.
func CreatedByUserIDNEQ(v uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDIn applies the In predicate on the "created_by_user_id" field.
func CreatedByUserIDIn(vs ...uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDNotIn applies the NotIn predicate on the "created_by_user_id" field.
func CreatedByUserIDNotIn(vs ...uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDIsNil applies the IsNil predicate on the "created_by_user_id" field.
func CreatedByUserIDIsNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIsNull(FieldCreatedByUserID))
}

// CreatedByUserIDNotNil applies the NotNil predicate on the "created_by_user_id" field.
func CreatedByUserIDNotNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotNull(FieldCreatedByUserID))
}

// CreatedByAgentIDEQ applies the EQ predicate on the "created_by_agent_id" field.
func CreatedByAgentIDEQ(v uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldCreatedByAgentID, v))
}

// CreatedByAgentIDNEQ applies the NEQ predicate on the "created_by_agent_id" field.
func CreatedByAgentIDNEQ(v uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldCreatedByAgentID, v))
}

// CreatedByAgentIDIn applies the In predicate on the "created_by_agent_id" field.
func CreatedByAgentIDIn(vs ...uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldCreatedByAgentID, vs...))
}

// CreatedByAgentIDNotIn applies the NotIn predicate on the "created_by_agent_id" field.
func CreatedByAgentIDNotIn(vs ...uuid.UUID) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldCreatedByAgentID, vs...))
}

// CreatedByAgentIDIsNil applies the IsNil predicate on the "created_by_agent_id" field.
func CreatedByAgentIDIsNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIsNull(FieldCreatedByAgentID))
}

// CreatedByAgentIDNotNil applies the NotNil predicate on the "created_by_agent_id" field.
func CreatedByAgentIDNotNil() predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotNull(FieldCreatedByAgentID))
}

// CreatedEQ applies the EQ predicate on the "created" field.
func CreatedEQ(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldCreated, v))
}

// CreatedNEQ applies the NEQ predicate on the "created" field.
func CreatedNEQ(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldCreated, v))
}

// CreatedIn applies the In predicate on the "created" field.
func CreatedIn(vs ...time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldCreated, vs...))
}

// CreatedNotIn applies the NotIn predicate on the "created" field.
func CreatedNotIn(vs ...time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldCreated, vs...))
}

// CreatedGT applies the GT predicate on the "created" field.
func CreatedGT(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldCreated, v))
}

// CreatedGTE applies the GTE predicate on the "created" field.
func CreatedGTE(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldCreated, v))
}

// CreatedLT applies the LT predicate on the "created" field.
func CreatedLT(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldCreated, v))
}

// CreatedLTE applies the LTE predicate on the "created" field.
func CreatedLTE(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldCreated, v))
}

// UpdatedEQ applies the EQ predicate on the "updated" field.
func UpdatedEQ(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldEQ(FieldUpdated, v))
}

// UpdatedNEQ applies the NEQ predicate on the "updated" field.
func UpdatedNEQ(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNEQ(FieldUpdated, v))
}

// UpdatedIn applies the In predicate on the "updated" field.
func UpdatedIn(vs ...time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldIn(FieldUpdated, vs...))
}

// UpdatedNotIn applies the NotIn predicate on the "updated" field.
func UpdatedNotIn(vs ...time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldNotIn(FieldUpdated, vs...))
}

// UpdatedGT applies the GT predicate on the "updated" field.
func UpdatedGT(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGT(FieldUpdated, v))
}

// UpdatedGTE applies the GTE predicate on the "updated" field.
func UpdatedGTE(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldGTE(FieldUpdated, v))
}

// UpdatedLT applies the LT predicate on the "updated" field.
func UpdatedLT(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLT(FieldUpdated, v))
}

// UpdatedLTE applies the LTE predicate on the "updated" field.
func UpdatedLTE(v time.Time) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.FieldLTE(FieldUpdated, v))
}

// HasGrove applies the HasEdge predicate on the "grove" edge.
func HasGrove() predicate.WorkflowRun {
	return predicate.WorkflowRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroveTable, GroveColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroveWith applies the HasEdge predicate on the "grove" edge with a given conditions (other predicates).
func HasGroveWith(preds ...predicate.Grove) predicate.WorkflowRun {
	return predicate.WorkflowRun(func(s *sql.Selector) {
		step := newGroveStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreatedByUser applies the HasEdge predicate on the "created_by_user" edge.
func HasCreatedByUser() predicate.WorkflowRun {
	return predicate.WorkflowRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatedByUserTable, CreatedByUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatedByUserWith applies the HasEdge predicate on the "created_by_user" edge with a given conditions (other predicates).
func HasCreatedByUserWith(preds ...predicate.User) predicate.WorkflowRun {
	return predicate.WorkflowRun(func(s *sql.Selector) {
		step := newCreatedByUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreatedByAgent applies the HasEdge predicate on the "created_by_agent" edge.
func HasCreatedByAgent() predicate.WorkflowRun {
	return predicate.WorkflowRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatedByAgentTable, CreatedByAgentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatedByAgentWith applies the HasEdge predicate on the "created_by_agent" edge with a given conditions (other predicates).
func HasCreatedByAgentWith(preds ...predicate.Agent) predicate.WorkflowRun {
	return predicate.WorkflowRun(func(s *sql.Selector) {
		step := newCreatedByAgentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkflowRun) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkflowRun) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkflowRun) predicate.WorkflowRun {
	return predicate.WorkflowRun(sql.NotPredicates(p))
}
