// Code generated by ent, DO NOT EDIT.

package workflowrun

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the workflowrun type in the database.
	Label = "workflow_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGroveID holds the string denoting the grove_id field in the database.
	FieldGroveID = "grove_id"
	// FieldBrokerID holds the string denoting the broker_id field in the database.
	FieldBrokerID = "broker_id"
	// FieldSourceYaml holds the string denoting the source_yaml field in the database.
	FieldSourceYaml = "source_yaml"
	// FieldInputsJSON holds the string denoting the inputs_json field in the database.
	FieldInputsJSON = "inputs_json"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldResultJSON holds the string denoting the result_json field in the database.
	FieldResultJSON = "result_json"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldTraceURL holds the string denoting the trace_url field in the database.
	FieldTraceURL = "trace_url"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldCreatedByUserID holds the string denoting the created_by_user_id field in the database.
	FieldCreatedByUserID = "created_by_user_id"
	// FieldCreatedByAgentID holds the string denoting the created_by_agent_id field in the database.
	FieldCreatedByAgentID = "created_by_agent_id"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// FieldUpdated holds the string denoting the updated field in the database.
	FieldUpdated = "updated"
	// EdgeGrove holds the string denoting the grove edge name in mutations.
	EdgeGrove = "grove"
	// EdgeCreatedByUser holds the string denoting the created_by_user edge name in mutations.
	EdgeCreatedByUser = "created_by_user"
	// EdgeCreatedByAgent holds the string denoting the created_by_agent edge name in mutations.
	EdgeCreatedByAgent = "created_by_agent"
	// Table holds the table name of the workflowrun in the database.
	Table = "workflow_runs"
	// GroveTable is the table that holds the grove relation/edge.
	GroveTable = "workflow_runs"
	// GroveInverseTable is the table name for the Grove entity.
	// It exists in this package in order to avoid circular dependency with the "grove" package.
	GroveInverseTable = "groves"
	// GroveColumn is the table column denoting the grove relation/edge.
	GroveColumn = "grove_id"
	// CreatedByUserTable is the table that holds the created_by_user relation/edge.
	CreatedByUserTable = "workflow_runs"
	// CreatedByUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatedByUserInverseTable = "users"
	// CreatedByUserColumn is the table column denoting the created_by_user relation/edge.
	CreatedByUserColumn = "created_by_user_id"
	// CreatedByAgentTable is the table that holds the created_by_agent relation/edge.
	CreatedByAgentTable = "workflow_runs"
	// CreatedByAgentInverseTable is the table name for the Agent entity.
	// It exists in this package in order to avoid circular dependency with the "agent" package.
	CreatedByAgentInverseTable = "agents"
	// CreatedByAgentColumn is the table column denoting the created_by_agent relation/edge.
	CreatedByAgentColumn = "created_by_agent_id"
)

// Columns holds all SQL columns for workflowrun fields.
var Columns = []string{
	FieldID,
	FieldGroveID,
	FieldBrokerID,
	FieldSourceYaml,
	FieldInputsJSON,
	FieldStatus,
	FieldResultJSON,
	FieldErrorMessage,
	FieldTraceURL,
	FieldStartedAt,
	FieldFinishedAt,
	FieldCreatedByUserID,
	FieldCreatedByAgentID,
	FieldCreated,
	FieldUpdated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreated holds the default value on creation for the "created" field.
	DefaultCreated func() time.Time
	// DefaultUpdated holds the default value on creation for the "updated" field.
	DefaultUpdated func() time.Time
	// UpdateDefaultUpdated holds the default value on update for the "updated" field.
	UpdateDefaultUpdated func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusQueued is the default value of the Status enum.
const DefaultStatus = StatusQueued

// Status values.
const (
	StatusQueued       Status = "queued"
	StatusProvisioning Status = "provisioning"
	StatusRunning      Status = "running"
	StatusSucceeded    Status = "succeeded"
	StatusFailed       Status = "failed"
	StatusCanceled     Status = "canceled"
	StatusTimedOut     Status = "timed_out"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusQueued, StatusProvisioning, StatusRunning, StatusSucceeded, StatusFailed, StatusCanceled, StatusTimedOut:
		return nil
	default:
		return fmt.Errorf("workflowrun: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the WorkflowRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGroveID orders the results by the grove_id field.
func ByGroveID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroveID, opts...).ToFunc()
}

// ByBrokerID orders the results by the broker_id field.
func ByBrokerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrokerID, opts...).ToFunc()
}

// BySourceYaml orders the results by the source_yaml field.
func BySourceYaml(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceYaml, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByTraceURL orders the results by the trace_url field.
func ByTraceURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraceURL, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByCreatedByUserID orders the results by the created_by_user_id field.
func ByCreatedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByUserID, opts...).ToFunc()
}

// ByCreatedByAgentID orders the results by the created_by_agent_id field.
func ByCreatedByAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByAgentID, opts...).ToFunc()
}

// ByCreated orders the results by the created field.
func ByCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreated, opts...).ToFunc()
}

// ByUpdated orders the results by the updated field.
func ByUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdated, opts...).ToFunc()
}

// ByGroveField orders the results by grove field.
func ByGroveField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroveStep(), sql.OrderByField(field, opts...))
	}
}

// ByCreatedByUserField orders the results by created_by_user field.
func ByCreatedByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedByUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByCreatedByAgentField orders the results by created_by_agent field.
func ByCreatedByAgentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedByAgentStep(), sql.OrderByField(field, opts...))
	}
}
func newGroveStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroveInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroveTable, GroveColumn),
	)
}
func newCreatedByUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedByUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatedByUserTable, CreatedByUserColumn),
	)
}
func newCreatedByAgentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedByAgentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatedByAgentTable, CreatedByAgentColumn),
	)
}
