// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agent"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/grove"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/user"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/workflowrun"
	"github.com/google/uuid"
)

// WorkflowRunUpdate is the builder for updating WorkflowRun entities.
type WorkflowRunUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowRunMutation
}

// Where appends a list predicates to the WorkflowRunUpdate builder.
func (_u *WorkflowRunUpdate) Where(ps ...predicate.WorkflowRun) *WorkflowRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroveID sets the "grove_id" field.
func (_u *WorkflowRunUpdate) SetGroveID(v uuid.UUID) *WorkflowRunUpdate {
	_u.mutation.SetGroveID(v)
	return _u
}

// SetNillableGroveID sets the "grove_id" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableGroveID(v *uuid.UUID) *WorkflowRunUpdate {
	if v != nil {
		_u.SetGroveID(*v)
	}
	return _u
}

// SetBrokerID sets the "broker_id" field.
func (_u *WorkflowRunUpdate) SetBrokerID(v string) *WorkflowRunUpdate {
	_u.mutation.SetBrokerID(v)
	return _u
}

// SetNillableBrokerID sets the "broker_id" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableBrokerID(v *string) *WorkflowRunUpdate {
	if v != nil {
		_u.SetBrokerID(*v)
	}
	return _u
}

// ClearBrokerID clears the value of the "broker_id" field.
func (_u *WorkflowRunUpdate) ClearBrokerID() *WorkflowRunUpdate {
	_u.mutation.ClearBrokerID()
	return _u
}

// SetSourceYaml sets the "source_yaml" field.
func (_u *WorkflowRunUpdate) SetSourceYaml(v string) *WorkflowRunUpdate {
	_u.mutation.SetSourceYaml(v)
	return _u
}

// SetNillableSourceYaml sets the "source_yaml" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableSourceYaml(v *string) *WorkflowRunUpdate {
	if v != nil {
		_u.SetSourceYaml(*v)
	}
	return _u
}

// SetInputsJSON sets the "inputs_json" field.
func (_u *WorkflowRunUpdate) SetInputsJSON(v []byte) *WorkflowRunUpdate {
	_u.mutation.SetInputsJSON(v)
	return _u
}

// ClearInputsJSON clears the value of the "inputs_json" field.
func (_u *WorkflowRunUpdate) ClearInputsJSON() *WorkflowRunUpdate {
	_u.mutation.ClearInputsJSON()
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkflowRunUpdate) SetStatus(v workflowrun.Status) *WorkflowRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableStatus(v *workflowrun.Status) *WorkflowRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResultJSON sets the "result_json" field.
func (_u *WorkflowRunUpdate) SetResultJSON(v []byte) *WorkflowRunUpdate {
	_u.mutation.SetResultJSON(v)
	return _u
}

// ClearResultJSON clears the value of the "result_json" field.
func (_u *WorkflowRunUpdate) ClearResultJSON() *WorkflowRunUpdate {
	_u.mutation.ClearResultJSON()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *WorkflowRunUpdate) SetErrorMessage(v string) *WorkflowRunUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableErrorMessage(v *string) *WorkflowRunUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *WorkflowRunUpdate) ClearErrorMessage() *WorkflowRunUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetTraceURL sets the "trace_url" field.
func (_u *WorkflowRunUpdate) SetTraceURL(v string) *WorkflowRunUpdate {
	_u.mutation.SetTraceURL(v)
	return _u
}

// SetNillableTraceURL sets the "trace_url" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableTraceURL(v *string) *WorkflowRunUpdate {
	if v != nil {
		_u.SetTraceURL(*v)
	}
	return _u
}

// ClearTraceURL clears the value of the "trace_url" field.
func (_u *WorkflowRunUpdate) ClearTraceURL() *WorkflowRunUpdate {
	_u.mutation.ClearTraceURL()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *WorkflowRunUpdate) SetStartedAt(v time.Time) *WorkflowRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableStartedAt(v *time.Time) *WorkflowRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *WorkflowRunUpdate) ClearStartedAt() *WorkflowRunUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *WorkflowRunUpdate) SetFinishedAt(v time.Time) *WorkflowRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableFinishedAt(v *time.Time) *WorkflowRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *WorkflowRunUpdate) ClearFinishedAt() *WorkflowRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *WorkflowRunUpdate) SetCreatedByUserID(v uuid.UUID) *WorkflowRunUpdate {
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableCreatedByUserID(v *uuid.UUID) *WorkflowRunUpdate {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (_u *WorkflowRunUpdate) ClearCreatedByUserID() *WorkflowRunUpdate {
	_u.mutation.ClearCreatedByUserID()
	return _u
}

// SetCreatedByAgentID sets the "created_by_agent_id" field.
func (_u *WorkflowRunUpdate) SetCreatedByAgentID(v uuid.UUID) *WorkflowRunUpdate {
	_u.mutation.SetCreatedByAgentID(v)
	return _u
}

// SetNillableCreatedByAgentID sets the "created_by_agent_id" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableCreatedByAgentID(v *uuid.UUID) *WorkflowRunUpdate {
	if v != nil {
		_u.SetCreatedByAgentID(*v)
	}
	return _u
}

// ClearCreatedByAgentID clears the value of the "created_by_agent_id" field.
func (_u *WorkflowRunUpdate) ClearCreatedByAgentID() *WorkflowRunUpdate {
	_u.mutation.ClearCreatedByAgentID()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *WorkflowRunUpdate) SetUpdated(v time.Time) *WorkflowRunUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetGrove sets the "grove" edge to the Grove entity.
func (_u *WorkflowRunUpdate) SetGrove(v *Grove) *WorkflowRunUpdate {
	return _u.SetGroveID(v.ID)
}

// SetCreatedByUser sets the "created_by_user" edge to the User entity.
func (_u *WorkflowRunUpdate) SetCreatedByUser(v *User) *WorkflowRunUpdate {
	return _u.SetCreatedByUserID(v.ID)
}

// SetCreatedByAgent sets the "created_by_agent" edge to the Agent entity.
func (_u *WorkflowRunUpdate) SetCreatedByAgent(v *Agent) *WorkflowRunUpdate {
	return _u.SetCreatedByAgentID(v.ID)
}

// Mutation returns the WorkflowRunMutation object of the builder.
func (_u *WorkflowRunUpdate) Mutation() *WorkflowRunMutation {
	return _u.mutation
}

// ClearGrove clears the "grove" edge to the Grove entity.
func (_u *WorkflowRunUpdate) ClearGrove() *WorkflowRunUpdate {
	_u.mutation.ClearGrove()
	return _u
}

// ClearCreatedByUser clears the "created_by_user" edge to the User entity.
func (_u *WorkflowRunUpdate) ClearCreatedByUser() *WorkflowRunUpdate {
	_u.mutation.ClearCreatedByUser()
	return _u
}

// ClearCreatedByAgent clears the "created_by_agent" edge to the Agent entity.
func (_u *WorkflowRunUpdate) ClearCreatedByAgent() *WorkflowRunUpdate {
	_u.mutation.ClearCreatedByAgent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkflowRunUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkflowRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkflowRunUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := workflowrun.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowRunUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := workflowrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.status": %w`, err)}
		}
	}
	if _u.mutation.GroveCleared() && len(_u.mutation.GroveIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkflowRun.grove"`)
	}
	return nil
}

func (_u *WorkflowRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowrun.Table, workflowrun.Columns, sqlgraph.NewFieldSpec(workflowrun.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BrokerID(); ok {
		_spec.SetField(workflowrun.FieldBrokerID, field.TypeString, value)
	}
	if _u.mutation.BrokerIDCleared() {
		_spec.ClearField(workflowrun.FieldBrokerID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceYaml(); ok {
		_spec.SetField(workflowrun.FieldSourceYaml, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputsJSON(); ok {
		_spec.SetField(workflowrun.FieldInputsJSON, field.TypeBytes, value)
	}
	if _u.mutation.InputsJSONCleared() {
		_spec.ClearField(workflowrun.FieldInputsJSON, field.TypeBytes)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workflowrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResultJSON(); ok {
		_spec.SetField(workflowrun.FieldResultJSON, field.TypeBytes, value)
	}
	if _u.mutation.ResultJSONCleared() {
		_spec.ClearField(workflowrun.FieldResultJSON, field.TypeBytes)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(workflowrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(workflowrun.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.TraceURL(); ok {
		_spec.SetField(workflowrun.FieldTraceURL, field.TypeString, value)
	}
	if _u.mutation.TraceURLCleared() {
		_spec.ClearField(workflowrun.FieldTraceURL, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(workflowrun.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(workflowrun.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(workflowrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(workflowrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(workflowrun.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.GroveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.GroveTable,
			Columns: []string{workflowrun.GroveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grove.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.GroveTable,
			Columns: []string{workflowrun.GroveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grove.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.CreatedByUserTable,
			Columns: []string{workflowrun.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.CreatedByUserTable,
			Columns: []string{workflowrun.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByAgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.CreatedByAgentTable,
			Columns: []string{workflowrun.CreatedByAgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByAgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.CreatedByAgentTable,
			Columns: []string{workflowrun.CreatedByAgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkflowRunUpdateOne is the builder for updating a single WorkflowRun entity.
type WorkflowRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowRunMutation
}

// SetGroveID sets the "grove_id" field.
func (_u *WorkflowRunUpdateOne) SetGroveID(v uuid.UUID) *WorkflowRunUpdateOne {
	_u.mutation.SetGroveID(v)
	return _u
}

// SetNillableGroveID sets the "grove_id" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableGroveID(v *uuid.UUID) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetGroveID(*v)
	}
	return _u
}

// SetBrokerID sets the "broker_id" field.
func (_u *WorkflowRunUpdateOne) SetBrokerID(v string) *WorkflowRunUpdateOne {
	_u.mutation.SetBrokerID(v)
	return _u
}

// SetNillableBrokerID sets the "broker_id" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableBrokerID(v *string) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetBrokerID(*v)
	}
	return _u
}

// ClearBrokerID clears the value of the "broker_id" field.
func (_u *WorkflowRunUpdateOne) ClearBrokerID() *WorkflowRunUpdateOne {
	_u.mutation.ClearBrokerID()
	return _u
}

// SetSourceYaml sets the "source_yaml" field.
func (_u *WorkflowRunUpdateOne) SetSourceYaml(v string) *WorkflowRunUpdateOne {
	_u.mutation.SetSourceYaml(v)
	return _u
}

// SetNillableSourceYaml sets the "source_yaml" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableSourceYaml(v *string) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetSourceYaml(*v)
	}
	return _u
}

// SetInputsJSON sets the "inputs_json" field.
func (_u *WorkflowRunUpdateOne) SetInputsJSON(v []byte) *WorkflowRunUpdateOne {
	_u.mutation.SetInputsJSON(v)
	return _u
}

// ClearInputsJSON clears the value of the "inputs_json" field.
func (_u *WorkflowRunUpdateOne) ClearInputsJSON() *WorkflowRunUpdateOne {
	_u.mutation.ClearInputsJSON()
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkflowRunUpdateOne) SetStatus(v workflowrun.Status) *WorkflowRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableStatus(v *workflowrun.Status) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResultJSON sets the "result_json" field.
func (_u *WorkflowRunUpdateOne) SetResultJSON(v []byte) *WorkflowRunUpdateOne {
	_u.mutation.SetResultJSON(v)
	return _u
}

// ClearResultJSON clears the value of the "result_json" field.
func (_u *WorkflowRunUpdateOne) ClearResultJSON() *WorkflowRunUpdateOne {
	_u.mutation.ClearResultJSON()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *WorkflowRunUpdateOne) SetErrorMessage(v string) *WorkflowRunUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableErrorMessage(v *string) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *WorkflowRunUpdateOne) ClearErrorMessage() *WorkflowRunUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetTraceURL sets the "trace_url" field.
func (_u *WorkflowRunUpdateOne) SetTraceURL(v string) *WorkflowRunUpdateOne {
	_u.mutation.SetTraceURL(v)
	return _u
}

// SetNillableTraceURL sets the "trace_url" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableTraceURL(v *string) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetTraceURL(*v)
	}
	return _u
}

// ClearTraceURL clears the value of the "trace_url" field.
func (_u *WorkflowRunUpdateOne) ClearTraceURL() *WorkflowRunUpdateOne {
	_u.mutation.ClearTraceURL()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *WorkflowRunUpdateOne) SetStartedAt(v time.Time) *WorkflowRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableStartedAt(v *time.Time) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *WorkflowRunUpdateOne) ClearStartedAt() *WorkflowRunUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *WorkflowRunUpdateOne) SetFinishedAt(v time.Time) *WorkflowRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableFinishedAt(v *time.Time) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *WorkflowRunUpdateOne) ClearFinishedAt() *WorkflowRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *WorkflowRunUpdateOne) SetCreatedByUserID(v uuid.UUID) *WorkflowRunUpdateOne {
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableCreatedByUserID(v *uuid.UUID) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (_u *WorkflowRunUpdateOne) ClearCreatedByUserID() *WorkflowRunUpdateOne {
	_u.mutation.ClearCreatedByUserID()
	return _u
}

// SetCreatedByAgentID sets the "created_by_agent_id" field.
func (_u *WorkflowRunUpdateOne) SetCreatedByAgentID(v uuid.UUID) *WorkflowRunUpdateOne {
	_u.mutation.SetCreatedByAgentID(v)
	return _u
}

// SetNillableCreatedByAgentID sets the "created_by_agent_id" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableCreatedByAgentID(v *uuid.UUID) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetCreatedByAgentID(*v)
	}
	return _u
}

// ClearCreatedByAgentID clears the value of the "created_by_agent_id" field.
func (_u *WorkflowRunUpdateOne) ClearCreatedByAgentID() *WorkflowRunUpdateOne {
	_u.mutation.ClearCreatedByAgentID()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *WorkflowRunUpdateOne) SetUpdated(v time.Time) *WorkflowRunUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetGrove sets the "grove" edge to the Grove entity.
func (_u *WorkflowRunUpdateOne) SetGrove(v *Grove) *WorkflowRunUpdateOne {
	return _u.SetGroveID(v.ID)
}

// SetCreatedByUser sets the "created_by_user" edge to the User entity.
func (_u *WorkflowRunUpdateOne) SetCreatedByUser(v *User) *WorkflowRunUpdateOne {
	return _u.SetCreatedByUserID(v.ID)
}

// SetCreatedByAgent sets the "created_by_agent" edge to the Agent entity.
func (_u *WorkflowRunUpdateOne) SetCreatedByAgent(v *Agent) *WorkflowRunUpdateOne {
	return _u.SetCreatedByAgentID(v.ID)
}

// Mutation returns the WorkflowRunMutation object of the builder.
func (_u *WorkflowRunUpdateOne) Mutation() *WorkflowRunMutation {
	return _u.mutation
}

// ClearGrove clears the "grove" edge to the Grove entity.
func (_u *WorkflowRunUpdateOne) ClearGrove() *WorkflowRunUpdateOne {
	_u.mutation.ClearGrove()
	return _u
}

// ClearCreatedByUser clears the "created_by_user" edge to the User entity.
func (_u *WorkflowRunUpdateOne) ClearCreatedByUser() *WorkflowRunUpdateOne {
	_u.mutation.ClearCreatedByUser()
	return _u
}

// ClearCreatedByAgent clears the "created_by_agent" edge to the Agent entity.
func (_u *WorkflowRunUpdateOne) ClearCreatedByAgent() *WorkflowRunUpdateOne {
	_u.mutation.ClearCreatedByAgent()
	return _u
}

// Where appends a list predicates to the WorkflowRunUpdate builder.
func (_u *WorkflowRunUpdateOne) Where(ps ...predicate.WorkflowRun) *WorkflowRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkflowRunUpdateOne) Select(field string, fields ...string) *WorkflowRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkflowRun entity.
func (_u *WorkflowRunUpdateOne) Save(ctx context.Context) (*WorkflowRun, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowRunUpdateOne) SaveX(ctx context.Context) *WorkflowRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkflowRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkflowRunUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := workflowrun.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowRunUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := workflowrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.status": %w`, err)}
		}
	}
	if _u.mutation.GroveCleared() && len(_u.mutation.GroveIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkflowRun.grove"`)
	}
	return nil
}

func (_u *WorkflowRunUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowrun.Table, workflowrun.Columns, sqlgraph.NewFieldSpec(workflowrun.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowrun.FieldID)
		for _, f := range fields {
			if !workflowrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflowrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BrokerID(); ok {
		_spec.SetField(workflowrun.FieldBrokerID, field.TypeString, value)
	}
	if _u.mutation.BrokerIDCleared() {
		_spec.ClearField(workflowrun.FieldBrokerID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceYaml(); ok {
		_spec.SetField(workflowrun.FieldSourceYaml, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputsJSON(); ok {
		_spec.SetField(workflowrun.FieldInputsJSON, field.TypeBytes, value)
	}
	if _u.mutation.InputsJSONCleared() {
		_spec.ClearField(workflowrun.FieldInputsJSON, field.TypeBytes)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workflowrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResultJSON(); ok {
		_spec.SetField(workflowrun.FieldResultJSON, field.TypeBytes, value)
	}
	if _u.mutation.ResultJSONCleared() {
		_spec.ClearField(workflowrun.FieldResultJSON, field.TypeBytes)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(workflowrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(workflowrun.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.TraceURL(); ok {
		_spec.SetField(workflowrun.FieldTraceURL, field.TypeString, value)
	}
	if _u.mutation.TraceURLCleared() {
		_spec.ClearField(workflowrun.FieldTraceURL, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(workflowrun.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(workflowrun.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(workflowrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(workflowrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(workflowrun.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.GroveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.GroveTable,
			Columns: []string{workflowrun.GroveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grove.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.GroveTable,
			Columns: []string{workflowrun.GroveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grove.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.CreatedByUserTable,
			Columns: []string{workflowrun.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.CreatedByUserTable,
			Columns: []string{workflowrun.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByAgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.CreatedByAgentTable,
			Columns: []string{workflowrun.CreatedByAgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByAgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.CreatedByAgentTable,
			Columns: []string{workflowrun.CreatedByAgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WorkflowRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
