// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agent"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/grove"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/user"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/workflowrun"
	"github.com/google/uuid"
)

// WorkflowRunCreate is the builder for creating a WorkflowRun entity.
type WorkflowRunCreate struct {
	config
	mutation *WorkflowRunMutation
	hooks    []Hook
}

// SetGroveID sets the "grove_id" field.
func (_c *WorkflowRunCreate) SetGroveID(v uuid.UUID) *WorkflowRunCreate {
	_c.mutation.SetGroveID(v)
	return _c
}

// SetBrokerID sets the "broker_id" field.
func (_c *WorkflowRunCreate) SetBrokerID(v string) *WorkflowRunCreate {
	_c.mutation.SetBrokerID(v)
	return _c
}

// SetNillableBrokerID sets the "broker_id" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableBrokerID(v *string) *WorkflowRunCreate {
	if v != nil {
		_c.SetBrokerID(*v)
	}
	return _c
}

// SetSourceYaml sets the "source_yaml" field.
func (_c *WorkflowRunCreate) SetSourceYaml(v string) *WorkflowRunCreate {
	_c.mutation.SetSourceYaml(v)
	return _c
}

// SetInputsJSON sets the "inputs_json" field.
func (_c *WorkflowRunCreate) SetInputsJSON(v []byte) *WorkflowRunCreate {
	_c.mutation.SetInputsJSON(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *WorkflowRunCreate) SetStatus(v workflowrun.Status) *WorkflowRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableStatus(v *workflowrun.Status) *WorkflowRunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetResultJSON sets the "result_json" field.
func (_c *WorkflowRunCreate) SetResultJSON(v []byte) *WorkflowRunCreate {
	_c.mutation.SetResultJSON(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *WorkflowRunCreate) SetErrorMessage(v string) *WorkflowRunCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableErrorMessage(v *string) *WorkflowRunCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetTraceURL sets the "trace_url" field.
func (_c *WorkflowRunCreate) SetTraceURL(v string) *WorkflowRunCreate {
	_c.mutation.SetTraceURL(v)
	return _c
}

// SetNillableTraceURL sets the "trace_url" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableTraceURL(v *string) *WorkflowRunCreate {
	if v != nil {
		_c.SetTraceURL(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *WorkflowRunCreate) SetStartedAt(v time.Time) *WorkflowRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableStartedAt(v *time.Time) *WorkflowRunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *WorkflowRunCreate) SetFinishedAt(v time.Time) *WorkflowRunCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableFinishedAt(v *time.Time) *WorkflowRunCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_c *WorkflowRunCreate) SetCreatedByUserID(v uuid.UUID) *WorkflowRunCreate {
	_c.mutation.SetCreatedByUserID(v)
	return _c
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableCreatedByUserID(v *uuid.UUID) *WorkflowRunCreate {
	if v != nil {
		_c.SetCreatedByUserID(*v)
	}
	return _c
}

// SetCreatedByAgentID sets the "created_by_agent_id" field.
func (_c *WorkflowRunCreate) SetCreatedByAgentID(v uuid.UUID) *WorkflowRunCreate {
	_c.mutation.SetCreatedByAgentID(v)
	return _c
}

// SetNillableCreatedByAgentID sets the "created_by_agent_id" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableCreatedByAgentID(v *uuid.UUID) *WorkflowRunCreate {
	if v != nil {
		_c.SetCreatedByAgentID(*v)
	}
	return _c
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (_c *WorkflowRunCreate) SetTimeoutSeconds(v int) *WorkflowRunCreate {
	_c.mutation.SetTimeoutSeconds(v)
	return _c
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableTimeoutSeconds(v *int) *WorkflowRunCreate {
	if v != nil {
		_c.SetTimeoutSeconds(*v)
	}
	return _c
}

// SetCreated sets the "created" field.
func (_c *WorkflowRunCreate) SetCreated(v time.Time) *WorkflowRunCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableCreated(v *time.Time) *WorkflowRunCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *WorkflowRunCreate) SetUpdated(v time.Time) *WorkflowRunCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableUpdated(v *time.Time) *WorkflowRunCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WorkflowRunCreate) SetID(v uuid.UUID) *WorkflowRunCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WorkflowRunCreate) SetNillableID(v *uuid.UUID) *WorkflowRunCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGrove sets the "grove" edge to the Grove entity.
func (_c *WorkflowRunCreate) SetGrove(v *Grove) *WorkflowRunCreate {
	return _c.SetGroveID(v.ID)
}

// SetCreatedByUser sets the "created_by_user" edge to the User entity.
func (_c *WorkflowRunCreate) SetCreatedByUser(v *User) *WorkflowRunCreate {
	return _c.SetCreatedByUserID(v.ID)
}

// SetCreatedByAgent sets the "created_by_agent" edge to the Agent entity.
func (_c *WorkflowRunCreate) SetCreatedByAgent(v *Agent) *WorkflowRunCreate {
	return _c.SetCreatedByAgentID(v.ID)
}

// Mutation returns the WorkflowRunMutation object of the builder.
func (_c *WorkflowRunCreate) Mutation() *WorkflowRunMutation {
	return _c.mutation
}

// Save creates the WorkflowRun in the database.
func (_c *WorkflowRunCreate) Save(ctx context.Context) (*WorkflowRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkflowRunCreate) SaveX(ctx context.Context) *WorkflowRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkflowRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkflowRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkflowRunCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := workflowrun.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := workflowrun.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := workflowrun.DefaultUpdated()
		_c.mutation.SetUpdated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := workflowrun.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkflowRunCreate) check() error {
	if _, ok := _c.mutation.GroveID(); !ok {
		return &ValidationError{Name: "grove_id", err: errors.New(`ent: missing required field "WorkflowRun.grove_id"`)}
	}
	if _, ok := _c.mutation.SourceYaml(); !ok {
		return &ValidationError{Name: "source_yaml", err: errors.New(`ent: missing required field "WorkflowRun.source_yaml"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WorkflowRun.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := workflowrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "WorkflowRun.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "WorkflowRun.updated"`)}
	}
	if len(_c.mutation.GroveIDs()) == 0 {
		return &ValidationError{Name: "grove", err: errors.New(`ent: missing required edge "WorkflowRun.grove"`)}
	}
	return nil
}

func (_c *WorkflowRunCreate) sqlSave(ctx context.Context) (*WorkflowRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkflowRunCreate) createSpec() (*WorkflowRun, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkflowRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workflowrun.Table, sqlgraph.NewFieldSpec(workflowrun.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.BrokerID(); ok {
		_spec.SetField(workflowrun.FieldBrokerID, field.TypeString, value)
		_node.BrokerID = &value
	}
	if value, ok := _c.mutation.SourceYaml(); ok {
		_spec.SetField(workflowrun.FieldSourceYaml, field.TypeString, value)
		_node.SourceYaml = value
	}
	if value, ok := _c.mutation.InputsJSON(); ok {
		_spec.SetField(workflowrun.FieldInputsJSON, field.TypeBytes, value)
		_node.InputsJSON = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(workflowrun.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ResultJSON(); ok {
		_spec.SetField(workflowrun.FieldResultJSON, field.TypeBytes, value)
		_node.ResultJSON = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(workflowrun.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.TraceURL(); ok {
		_spec.SetField(workflowrun.FieldTraceURL, field.TypeString, value)
		_node.TraceURL = &value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(workflowrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(workflowrun.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.TimeoutSeconds(); ok {
		_spec.SetField(workflowrun.FieldTimeoutSeconds, field.TypeInt, value)
		_node.TimeoutSeconds = &value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(workflowrun.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(workflowrun.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	if nodes := _c.mutation.GroveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.GroveTable,
			Columns: []string{workflowrun.GroveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grove.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroveID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.CreatedByUserTable,
			Columns: []string{workflowrun.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedByUserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatedByAgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowrun.CreatedByAgentTable,
			Columns: []string{workflowrun.CreatedByAgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedByAgentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WorkflowRunCreateBulk is the builder for creating many WorkflowRun entities in bulk.
type WorkflowRunCreateBulk struct {
	config
	err      error
	builders []*WorkflowRunCreate
}

// Save creates the WorkflowRun entities in the database.
func (_c *WorkflowRunCreateBulk) Save(ctx context.Context) ([]*WorkflowRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkflowRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkflowRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkflowRunCreateBulk) SaveX(ctx context.Context) []*WorkflowRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkflowRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkflowRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
