// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agent"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/grove"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/user"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/workflowrun"
	"github.com/google/uuid"
)

// WorkflowRun is the model entity for the WorkflowRun schema.
type WorkflowRun struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// GroveID holds the value of the "grove_id" field.
	GroveID uuid.UUID `json:"grove_id,omitempty"`
	// BrokerID holds the value of the "broker_id" field.
	BrokerID *string `json:"broker_id,omitempty"`
	// SourceYaml holds the value of the "source_yaml" field.
	SourceYaml string `json:"source_yaml,omitempty"`
	// InputsJSON holds the value of the "inputs_json" field.
	InputsJSON *[]byte `json:"inputs_json,omitempty"`
	// Status holds the value of the "status" field.
	Status workflowrun.Status `json:"status,omitempty"`
	// ResultJSON holds the value of the "result_json" field.
	ResultJSON *[]byte `json:"result_json,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// TraceURL holds the value of the "trace_url" field.
	TraceURL *string `json:"trace_url,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// CreatedByUserID holds the value of the "created_by_user_id" field.
	CreatedByUserID *uuid.UUID `json:"created_by_user_id,omitempty"`
	// CreatedByAgentID holds the value of the "created_by_agent_id" field.
	CreatedByAgentID *uuid.UUID `json:"created_by_agent_id,omitempty"`
	// User-specified timeout in seconds; nil means use server default
	TimeoutSeconds *int `json:"timeout_seconds,omitempty"`
	// Created holds the value of the "created" field.
	Created time.Time `json:"created,omitempty"`
	// Updated holds the value of the "updated" field.
	Updated time.Time `json:"updated,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkflowRunQuery when eager-loading is set.
	Edges        WorkflowRunEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WorkflowRunEdges holds the relations/edges for other nodes in the graph.
type WorkflowRunEdges struct {
	// Grove holds the value of the grove edge.
	Grove *Grove `json:"grove,omitempty"`
	// CreatedByUser holds the value of the created_by_user edge.
	CreatedByUser *User `json:"created_by_user,omitempty"`
	// CreatedByAgent holds the value of the created_by_agent edge.
	CreatedByAgent *Agent `json:"created_by_agent,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// GroveOrErr returns the Grove value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkflowRunEdges) GroveOrErr() (*Grove, error) {
	if e.Grove != nil {
		return e.Grove, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: grove.Label}
	}
	return nil, &NotLoadedError{edge: "grove"}
}

// CreatedByUserOrErr returns the CreatedByUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkflowRunEdges) CreatedByUserOrErr() (*User, error) {
	if e.CreatedByUser != nil {
		return e.CreatedByUser, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by_user"}
}

// CreatedByAgentOrErr returns the CreatedByAgent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkflowRunEdges) CreatedByAgentOrErr() (*Agent, error) {
	if e.CreatedByAgent != nil {
		return e.CreatedByAgent, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: agent.Label}
	}
	return nil, &NotLoadedError{edge: "created_by_agent"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkflowRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workflowrun.FieldCreatedByUserID, workflowrun.FieldCreatedByAgentID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case workflowrun.FieldInputsJSON, workflowrun.FieldResultJSON:
			values[i] = new([]byte)
		case workflowrun.FieldTimeoutSeconds:
			values[i] = new(sql.NullInt64)
		case workflowrun.FieldBrokerID, workflowrun.FieldSourceYaml, workflowrun.FieldStatus, workflowrun.FieldErrorMessage, workflowrun.FieldTraceURL:
			values[i] = new(sql.NullString)
		case workflowrun.FieldStartedAt, workflowrun.FieldFinishedAt, workflowrun.FieldCreated, workflowrun.FieldUpdated:
			values[i] = new(sql.NullTime)
		case workflowrun.FieldID, workflowrun.FieldGroveID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkflowRun fields.
func (_m *WorkflowRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workflowrun.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case workflowrun.FieldGroveID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field grove_id", values[i])
			} else if value != nil {
				_m.GroveID = *value
			}
		case workflowrun.FieldBrokerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field broker_id", values[i])
			} else if value.Valid {
				_m.BrokerID = new(string)
				*_m.BrokerID = value.String
			}
		case workflowrun.FieldSourceYaml:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_yaml", values[i])
			} else if value.Valid {
				_m.SourceYaml = value.String
			}
		case workflowrun.FieldInputsJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field inputs_json", values[i])
			} else if value != nil {
				_m.InputsJSON = value
			}
		case workflowrun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = workflowrun.Status(value.String)
			}
		case workflowrun.FieldResultJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field result_json", values[i])
			} else if value != nil {
				_m.ResultJSON = value
			}
		case workflowrun.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case workflowrun.FieldTraceURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trace_url", values[i])
			} else if value.Valid {
				_m.TraceURL = new(string)
				*_m.TraceURL = value.String
			}
		case workflowrun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case workflowrun.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case workflowrun.FieldCreatedByUserID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_user_id", values[i])
			} else if value.Valid {
				_m.CreatedByUserID = new(uuid.UUID)
				*_m.CreatedByUserID = *value.S.(*uuid.UUID)
			}
		case workflowrun.FieldCreatedByAgentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_agent_id", values[i])
			} else if value.Valid {
				_m.CreatedByAgentID = new(uuid.UUID)
				*_m.CreatedByAgentID = *value.S.(*uuid.UUID)
			}
		case workflowrun.FieldTimeoutSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeout_seconds", values[i])
			} else if value.Valid {
				_m.TimeoutSeconds = new(int)
				*_m.TimeoutSeconds = int(value.Int64)
			}
		case workflowrun.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				_m.Created = value.Time
			}
		case workflowrun.FieldUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated", values[i])
			} else if value.Valid {
				_m.Updated = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkflowRun.
// This includes values selected through modifiers, order, etc.
func (_m *WorkflowRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGrove queries the "grove" edge of the WorkflowRun entity.
func (_m *WorkflowRun) QueryGrove() *GroveQuery {
	return NewWorkflowRunClient(_m.config).QueryGrove(_m)
}

// QueryCreatedByUser queries the "created_by_user" edge of the WorkflowRun entity.
func (_m *WorkflowRun) QueryCreatedByUser() *UserQuery {
	return NewWorkflowRunClient(_m.config).QueryCreatedByUser(_m)
}

// QueryCreatedByAgent queries the "created_by_agent" edge of the WorkflowRun entity.
func (_m *WorkflowRun) QueryCreatedByAgent() *AgentQuery {
	return NewWorkflowRunClient(_m.config).QueryCreatedByAgent(_m)
}

// Update returns a builder for updating this WorkflowRun.
// Note that you need to call WorkflowRun.Unwrap() before calling this method if this WorkflowRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkflowRun) Update() *WorkflowRunUpdateOne {
	return NewWorkflowRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkflowRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkflowRun) Unwrap() *WorkflowRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkflowRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkflowRun) String() string {
	var builder strings.Builder
	builder.WriteString("WorkflowRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("grove_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroveID))
	builder.WriteString(", ")
	if v := _m.BrokerID; v != nil {
		builder.WriteString("broker_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("source_yaml=")
	builder.WriteString(_m.SourceYaml)
	builder.WriteString(", ")
	if v := _m.InputsJSON; v != nil {
		builder.WriteString("inputs_json=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.ResultJSON; v != nil {
		builder.WriteString("result_json=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TraceURL; v != nil {
		builder.WriteString("trace_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedByUserID; v != nil {
		builder.WriteString("created_by_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreatedByAgentID; v != nil {
		builder.WriteString("created_by_agent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TimeoutSeconds; v != nil {
		builder.WriteString("timeout_seconds=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(_m.Created.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated=")
	builder.WriteString(_m.Updated.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WorkflowRuns is a parsable slice of WorkflowRun.
type WorkflowRuns []*WorkflowRun
